### ISSUE TITLE
Game crashes when casting not on mirror

### ISSUE THREAD

**Issue by Ch1216** [enjarai/trickster#24] opened 2024-07-30 22:38 UTC
I was on a minecraft world opened to LAN, I used morph on another player, and the game crashed
The mods on both clients were trickster + required dependencies listed on modrinth + pehkui

[crash-2024-07-30_18.33.41-server.txt](https://github.com/user-attachments/files/16434079/crash-2024-07-30_18.33.41-server.txt)
[latest.log](https://github.com/user-attachments/files/16434080/latest.log)

**Comment by StellarWitch7** [comment] 2024-07-30 22:48
Hello. Reading the stack trace, this appears to be an issue with the new execution engine. Could you provide further details?

My questions are:
1. Which item did you use to cast the spell?
2. Is the server running in offline mode?
3. Is this issue reproducible with a minimum spell consisting only of a raycast and polymorph?

**Comment by Ch1216** [comment] 2024-07-30 23:10
1. I used a scroll in a top hat with a wand
2. I assume not since the skins the accounts had were the skins linekd to them
3. I tested it using only Reflection Delusion, Scout's Distortion and Polymorph Ploy, and it still crashed the game, I dont know how only using a raycast and polumorph would work if Polymorph needs 2 entity iotas

Also, additionally, the trick does work, when i opened back the world I looked like the other account, and name tags being the other's account, it actually confused me since I thought modrinth launcher bugged out due to having 2 instanced opened under different accounts, but I realized that it was just the trick when i typed in chat.

**Comment by StellarWitch7** [comment] 2024-07-30 23:19
LAN servers are typically in online mode, I was asking as polymorph is unsupported in offline mode, and wanted to be certain it wasn't that. 

Regarding "only using a raycast and polymorph", I apologize for my lack of clarity. I meant what you say you tested it with. 

If the trick worked, then I assume the spell progress was saved. Could you provide the output of running Showcase Stratagem on the wand's inscribed spell? (Or just type it up, if it's not too long... I assume it's a standard read-and-cast?)

**Comment by Ch1216** [comment] 2024-07-30 23:28
![ihadtosearchthegithubtofindwhereshowcasestratagemwas](https://github.com/user-attachments/assets/5b536ef2-0031-4d46-aec3-20b82b0c6586)
I assume this is what you wanted?

**Comment by StellarWitch7** [comment] 2024-07-30 23:30
Oh when you tested it you put it directly on the wand. Hm. Alright. 
Thanks for the info. We'll look into this when we can.

**Comment by Ch1216** [comment] 2024-07-30 23:36
I also wanted to mention that this might be more grand than just polymorph, I tried to do Reflection Delusion to Archer's Distortion to Ploy of Destruction, and my game crashed

[latest.log](https://github.com/user-attachments/files/16434319/latest.log)
[crash-2024-07-30_19.36.02-server.txt](https://github.com/user-attachments/files/16434321/crash-2024-07-30_19.36.02-server.txt)

**Comment by StellarWitch7** [comment] 2024-07-30 23:39
That is helpful information, as I cannot currently test Polymorph Ploy but I can certainly test Ploy of Destruction.

**Comment by StellarWitch7** [comment] 2024-07-30 23:53
Is this the spell you used? It works fine in singleplayer in my development environment. The last log you sent me was also in singleplayer, correct?
![image](https://github.com/user-attachments/assets/e20cbb65-554a-4dfd-a62c-789f97622a79)

Was your instance originally on a previous version of Trickster, and was updated to 2.0.0-alpha.3? Or is this a new instance?

**Comment by Ch1216** [comment] 2024-07-30 23:58
Yes its that spell, Yes it crashed on single player, my instance was always on 2.0.0-alpha.3
Also just found out Resonance Ploy is also crashing the game, so far only Ploy of Occupation is the only plot that does not crash me

**Comment by StellarWitch7** [comment] 2024-07-31 00:00
This is rather concerning. I'll keep poking about. Let us know if there are any changes to the situation.

**Comment by Ch1216** [comment] 2024-07-31 00:10
ok, so I think the problems is not any specific spell, but rather using a wand to cast anything, as casting change scale with wand and top hat+scroll the game crashes, but casting destroy block or resonance signal change with the mirror does not crash it

**Comment by StellarWitch7** [comment] 2024-07-31 00:11
> [...] Reading the stack trace, this appears to be an issue with the new execution engine. [...]

Seems like it.

**Comment by StellarWitch7** [comment] 2024-07-31 00:14
I've pulled `master` and will be testing to see if it is possibly fixed by https://github.com/enjarai/trickster/pull/23.

**Comment by StellarWitch7** [comment] 2024-07-31 00:23
I can confirm the issue on `master`, and so this is likely fixed by #23, where I tested it first. As the issue is with the new  queued execution engine, the mirror is unaffected. There is a tweak made in #23 that modifies this portion of the engine, unintentionally fixing it. 

Thank you for opening an issue. The fix should be there next release.

**Closed** 2024-08-01 07:49 UTC
